# Ce fichier configure la validation Symfony du backend GarageFlow.
# Il existe pour preparer les futures validations de DTO et d'entites.
# Les regles metier seront ajoutees plus tard dans les classes adaptees.
framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
